language: elixir
sudo: false
otp_release:
  - 20.0
elixir:
  - 1.4.5
env:
  global:
    - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
script:
  - mix test
  - mix dialyzer --halt-exit-status
  - mix credo --strict
notifications:
  email: false
